#!/bin/bash
# -----------------------------------------------------------------------
# This script interactively makes a Docker-based Plex Media Server
# based out of this directory creating the .env file containing
# the Plex Media Server's confguration
# -----------------------------------------------------------------------

# Makes a default Docker-based plex server based out of this directory

# Exit script on any errors
set -e

create_directory () {
  dir=$1
  echo " creating directory [${dir}]"
  # mkdir -p is non-destructive
  mkdir -p "${dir}"
  if [[ ! -d "${dir}" ]]; then
    echo "!!! ERROR: Unable to create directory [${dir}] !!!" 1>&2
    exit 66
  fi
  echo " ...directory [${dir}] created"
}

echo " >>>- CONFIGURING PLEXSERVER -<<<"
echo ""
echo " This script creates a container-based Plex Media Server based out of"
echo " this directory."
echo ""
echo " NOTE that it will NOT overwrite or destroy existing directories or files."
echo ""
read -p "Do you wish to proceed (Press any key to continue or 'n' to exit)? " response
if [[ $response == 'n' ]] || [[ $response == 'N' ]]; then
  echo " buh-bye"
  echo ""
  exit
fi

echo ""
current_user=$(whoami)
echo " Creating Plex Server for current user: ${current_user}"
current_uid=$(id -u $current_user)
current_gid=$(id -g $current_user)
echo "  current user UID: ${current_uid}"
echo "  current user GID: ${current_gid}"

echo ""
echo " Creating Plex Server Working Directories..."
plexserverdatadir="${PWD}/.plex-server/data"
create_directory "${plexserverdatadir}"

configdir="${plexserverdatadir}/config"
create_directory "${configdir}"

transcodedir="${plexserverdatadir}/transcode"
create_directory "${transcodedir}"

echo ""
echo " Enter the starting directory of your Media for the Plex Media Server..."
read -p "ENTER the full path with NO ending /: " plexservermedia
echo ""
echo " Setting Plex Media Server Media to [${plexservermedia}]"
if [[ ! -d "${plexservermedia}" ]]; then
  echo "!!! FYI, currently there is no directory at [${plexservermedia}] !!!"
fi

echo ""
echo " Configuring Environment Variables for Plex Media Server..."
plexuidenv="PLEX_UID=${current_uid}"
echo "  [${plexuidenv}]"
plexgidenv="PLEX_GID=${current_gid}"
echo "  [${plexgidenv}]"
configenv="PLEX_CONFIG=${configdir}"
echo "  [${configenv}]"
transcodeenv="PLEX_TRANSCODE=${transcodedir}"
echo "  [${transcodeenv}]"
plexmediaenv="PLEX_MEDIA=${plexservermedia}"
echo "  [${plexmediaenv}]"

echo " Creating .env file for Plex Server docker-compose..."
if [[ -f ".env" ]]; then
  echo "!!! ERROR: .env file already exists !!!" 1>&2
  exit 88
fi
echo " Writing .env file..."
echo "${plexuidenv}" >> ".env"
echo "${plexgidenv}" >> ".env"
echo "${configenv}" >> ".env"
echo "${transcodeenv}" >> ".env"
echo "${plexmediaenv}" >> ".env"

echo " Created .env file for Plex Media Server..."
echo "---------------------------------------------"
cat ".env"
echo "---------------------------------------------"

echo ""
echo " Your Plex Server is now ready to run..."
echo ""
echo ">>> peace out <<<"
echo ""
