#!/bin/bash
# Interactively runs the plex server based out of this directory
# using docker-compose

prompt-to-proceed () {
  echo ""
  read -p "Do you wish to proceed (Press any key to continue or 'n' to exit)? " response
  if [[ $response == 'n' ]] || [[ $response == 'N' ]]; then
    echo " buh-bye"
    echo ""
    exit
  fi
  echo ""
}

echo " >>>- STARTING PREVIOUSLY CONFIGURED PLEXSERVER -<<<"
echo ""
echo " This script interactively runs the default, previously configured"
echo " container-based Plex Media Server based out of this directory"

echo ""
echo " Checking if Docker is running..."
if (! docker stats --no-stream ); then
  echo ""
  echo "!!! Docker is not running, please start Docker and !!!"
  echo "!!! once Docker is fully started, re-run this script !!!"
  echo ""
  exit 86
fi
echo " ...Docker is running"
echo ""

echo " You will first need a Plex Server Claim Token"
echo " In a web browser, go to..."
echo "----------------------------------"
echo "--- https://www.plex.tv/claim/ ---"
echo "----------------------------------"
echo ""
read -p "ENTER the Plex Server Claim Code => " plexclaim
echo ""
plexclaimenvstring="PLEX_CLAIM=${plexclaim}"

dockercomposecmd="${plexclaimenvstring} docker-compose "

echo " The Plex Media Server Config..."
dcconfigcmd="${dockercomposecmd} config "
echo " $ ${dcconfigcmd}"
eval "${dcconfigcmd}"
echo ".............................................."

echo ""
echo " Ready to start Plex Media Server with [${dockercomposecmd}]"
prompt-to-proceed

echo " Starting Plex Media Server..."
dcupcmd="${dockercomposecmd} up -d "
echo "  $ ${dcupcmd}"
eval "${dcupcmd}"
echo ".............................................."

echo ""
echo " To Finish the Startup and Administer Plex Media Server"
echo " In a web browser, go to..."
echo "---------------------------"
echo "--- http://app.plex.tv/ ---"
echo "---------------------------"
echo " it will take a few minutes for your plexserver to start"
echo ""
echo " To STOP the Plex Media Server, enter this command..."
echo "$ ${dockercomposecmd} down"
echo ""
echo ">>> peace out <<<"
echo ""
