#!/bin/bash
# -----------------------------------------------------------------------
# This script interactively runs the previously created Plex Media Server
# based out of this directory using docker-compose and the confguration
# in the created .env file
#
# ASSUMES macOS specifically when getting the local host IP
#
# -----------------------------------------------------------------------

# Exit script on any errors
set -e

prompt-to-proceed () {
  echo ""
  read -p "Do you wish to proceed (Press any key to continue or 'n' to exit)? " response
  if [[ $response == 'n' ]] || [[ $response == 'N' ]]; then
    echo " buh-bye"
    echo ""
    exit
  fi
  echo ""
}

echo " >>>- STARTING PREVIOUSLY CONFIGURED PLEXSERVER -<<<"
echo ""
echo " This script interactively runs the default, previously configured"
echo " container-based Plex Media Server based out of this directory"

echo ""
echo " Checking if Docker is running..."
if (! docker stats --no-stream ); then
  echo ""
  echo "!!! Docker is not running, please start Docker and !!!"
  echo "!!! once Docker is fully started, re-run this script !!!"
  echo ""
  exit 86
fi
echo " ...Docker is running"
echo ""

echo " Setting the Advertise Address for Plex Media Server..."
# macOS https://apple.stackexchange.com/questions/20547/how-do-i-find-my-ip-address-from-the-command-line
host_ip=$(ipconfig getifaddr en0)
echo "  The local host IP is [${host_ip}]"
advertise_address="${host_ip}:32400/"
echo "  Advertise Address is [${advertise_address}]"
echo ""
export ADVERTISE_IP="${advertise_address}"
dockercomposecmdenv="ADVERTISE_IP=${advertise_address}"


echo " You will first need a Plex Server Claim Token"
echo " In a web browser, go to..."
echo "----------------------------------"
echo "--- https://www.plex.tv/claim/ ---"
echo "----------------------------------"
echo ""
read -p "ENTER the Plex Server Claim Code => " plexclaim
echo ""
export PLEX_CLAIM=${plexclaim}
dockercomposecmdenv="${dockercomposecmdenv} PLEX_CLAIM=${plexclaim}"

dockercomposecmd="docker-compose"

dcconfigcmd="${dockercomposecmd} config "
echo " The Plex Media Server Config [$dcconfigcmd]..."
$dcconfigcmd
echo ".............................................."

echo ""
dcupcmd="${dockercomposecmd} up -d "
echo " Ready to start Plex Media Server with [$dcupcmd]"
prompt-to-proceed
echo " Starting Plex Media Server..."
$dcupcmd
echo ".............................................."

echo ""
echo " To Finish the Startup and Administer Plex Media Server"
echo " In a web browser, go to..."
echo "-----------------------------------------------------"
echo "--- http://${advertise_address} ---"
echo "-----------------------------------------------------"
echo " it will take a few minutes for your plexserver to start"
echo ""
echo " To STOP the Plex Media Server, enter this command..."
echo "$ ${dockercomposecmdenv} ${dockercomposecmd} down"
echo ""
echo ">>> peace out <<<"
echo ""
